# Generated by Django 2.2.4 on 2023-05-25 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0003_horse_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horse',
            name='age',
        ),
        migrations.AddField(
            model_name='horse',
            name='breed',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
