# Generated by Django 2.2.4 on 2023-05-25 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0004_auto_20230525_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='horse',
            name='age',
            field=models.CharField(default=13, max_length=3),
            preserve_default=False,
        ),
    ]
